# Generated by Django 5.2.4 on 2025-07-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcontact',
            name='email_addr',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramcontact',
            name='chat_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
