# Generated by Django 5.2.4 on 2025-07-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_core', '0002_telegramcontact_email_addr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramcontact',
            name='username',
        ),
    ]
